# -*- coding: utf-8 -*-
"""Using Statistics library

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gkSkBgv4F-osQMYmG6yN6mZGjtT9LZ57

1.Write a Python program to declare a 1-D array. With the help of the statistics library, calculate the Mean, Median, and Mode.
"""

import numpy as np
import statistics as st

arr=np.array([1,2,3,4,5,6,2,3,4,5,5,5,5])
print("The Array is:",arr)
print("Mean of the Array is:",st.mean(arr))
print("Median of the Array is:",st.median(arr))
print("Mode of the array is :",st.mode(arr))

"""2.Write a Python program to declare a DataFrame as shown in the dataset section below and calculate the Mean, Median, and Mode of the entire DataFrame.

"""

import pandas as pd
df = pd.DataFrame([[10,20,30,40],[7,14,21,28],[55,15,8,12],[15,14,1,8],[7,1,1,8],[5,4,9,2]],
                   columns=['Apple','Orange','Banana','Pear'],
                   index=['Bag1','Bag2','Bag3','Bag4','Bag5','Bag6'])
display(df)
print("Calculating the mean:")
print(df.mean())
print("Calculating the median:")
print(df.median())
print("Calculating the mode:")
print(df.mode())

"""3.Load the “Books.csv”dataset into a DataFrame and perform the following tasks:
1.Perform   initial   analysis   on   the dataset   using   the info() and   the describe()functions
2.Group the data based on the "Author"column and calculate the average user ratings and average price,and write them in new columns
3.Find out which of the authorshave writtenthe maximum number of books
"""

import pandas as pd
df=pd.read_csv("Books.csv")

df.info()
df.describe(include='object')
display(df)

df1=df.groupby('Author')['User Rating'].mean().reset_index()
df1.rename(columns={'User Rating':'Avg_User_Rating'},inplace=True)
df1.head()

df2=df.groupby('Author')['Price'].mean().reset_index()
df2.rename(columns={'Price':'Avg_Price'},inplace=True)
df2.head()

print("Maximum number of books are written by:")
display(df['Author'].mode())